name: CI
on:
  - push
  - pull_request

jobs:
  one:
   runs-on: ubuntu-latest
   steps:
      - name: Create a file
        run: |
          echo "https://www.skippednote.com" > file

      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: arti
          path: ./file

  two:
   runs-on: ubuntu-latest
   steps:
      - name: Download file
        uses: actions/download-artifact@v2
        with:
          name: file
      
      - name: Print file
        run: |
          cat file